# Generated by Django 5.0.1 on 2024-01-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('price_ru', models.FloatField(verbose_name='Цена (руб.)')),
                ('price_kz', models.FloatField(verbose_name='Цена (тенге)')),
                ('description_ru', models.TextField(verbose_name='Описание продукта (ru)')),
                ('description_kz', models.TextField(verbose_name='Описание продукта (kz)')),
                ('catogory', models.ManyToManyField(to='api.categorymodel', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
