# Generated by Django 5.0.1 on 2024-01-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productmodel_catogory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='catogory',
            new_name='category',
        ),
    ]
