# Generated by Django 5.0.1 on 2024-02-28 08:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
                ('price_ru', models.FloatField(verbose_name='Цена (руб.)')),
                ('price_kz', models.FloatField(verbose_name='Цена (тенге)')),
                ('description_ru', models.TextField(verbose_name='Описание продукта (ru)')),
                ('description_kz', models.TextField(verbose_name='Описание продукта (kz)')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('content_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('is_public', models.BooleanField(verbose_name='Разместить')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фотография')),
                ('category', models.ManyToManyField(blank=True, to='api.categorymodel', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
