# Generated by Django 5.0.1 on 2024-03-06 09:25

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
            ],
            options={
                'verbose_name_plural': 'Категории Блог',
            },
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('telephon', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Формы',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
            ],
            options={
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
                ('price_ru', models.FloatField(verbose_name='Цена (руб.)')),
                ('price_kz', models.FloatField(verbose_name='Цена (тенге)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('description_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('content_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('is_public', models.BooleanField(verbose_name='Разместить')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ManyToManyField(blank=True, to='api.productcategorymodel', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
                ('price_ru', models.FloatField(verbose_name='Цена (руб.)')),
                ('price_kz', models.FloatField(verbose_name='Цена (тенге)')),
                ('description_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('description_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фотография')),
                ('category', models.ManyToManyField(blank=True, to='api.productcategorymodel', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='FormProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Число')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.formmodel', verbose_name='id Корзины')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel', verbose_name='id продкта')),
            ],
            options={
                'verbose_name_plural': 'Формы с продуктами',
            },
        ),
    ]
