# Generated by Django 5.0.1 on 2024-03-06 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formproductsmodel',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formmodel', verbose_name='id Корзины'),
        ),
    ]
