# Generated by Django 5.0.1 on 2024-03-01 22:51

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
            ],
            options={
                'verbose_name_plural': 'Категории продуктов',
            },
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='BlogCategoryModel',
        ),
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name_plural': 'Категории Блог'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='content_kz',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='is_public',
        ),
        migrations.CreateModel(
            name='FormProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Число')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel', verbose_name='id продкта')),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('telephon', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.formproductsmodel', verbose_name='Продукты')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (ru)')),
                ('title_kz', models.CharField(max_length=255, verbose_name='Название (kz)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Название (en)')),
                ('price_ru', models.FloatField(verbose_name='Цена (руб.)')),
                ('price_kz', models.FloatField(verbose_name='Цена (тенге)')),
                ('description_ru', models.TextField(verbose_name='Короткое описание (ru)')),
                ('description_kz', models.TextField(verbose_name='Короткое описание (kz)')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('content_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('is_public', models.BooleanField(verbose_name='Разместить')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ManyToManyField(blank=True, to='api.productcategorymodel', verbose_name='Категории')),
            ],
            options={
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.productcategorymodel', verbose_name='Категории'),
        ),
    ]
