# Generated by Django 5.0.1 on 2024-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='catogory',
            field=models.ManyToManyField(blank=True, to='api.categorymodel', verbose_name='Категории'),
        ),
    ]
