# Generated by Django 5.0.1 on 2024-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_formproductsmodel_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фотография'),
        ),
    ]
