# Generated by Django 5.0.1 on 2024-03-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='price_kz',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='price_ru',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description_kz',
            field=models.TextField(verbose_name='Короткое описание (kz)'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description_ru',
            field=models.TextField(verbose_name='Короткое описание (ru)'),
        ),
    ]
