# Generated by Django 5.0.1 on 2024-01-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_catogory_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фотография'),
        ),
    ]
