# Generated by Django 5.0.1 on 2024-03-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_blogmodel_price_kz_remove_blogmodel_price_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.ManyToManyField(to='api.blogcategorymodel', verbose_name='Категиории'),
        ),
    ]
