# Generated by Django 5.0.1 on 2024-03-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blogmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='category',
            field=models.ManyToManyField(blank=True, to='api.blogcategorymodel', verbose_name='Категиории'),
        ),
    ]
