# Generated by Django 5.0.1 on 2024-03-22 13:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blogmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('telephon', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Контактная форма',
            },
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-date_modified'], 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content_kz',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание (каз.)'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание (рус.)'),
        ),
    ]
