# Generated by Django 5.0.1 on 2024-03-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_contactform_contactformmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormModel',
            new_name='ProductFormModel',
        ),
    ]
