# Generated by Django 5.0.1 on 2024-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_formmodel_productformmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_photos/', verbose_name='Фотография')),
            ],
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='api.productimagemodel', verbose_name='Фотографии продукта'),
        ),
    ]
